### ISSUE TITLE
CODE REVIEWS

### ISSUE THREAD

**Issue by tcisse** [adeys/figma-to-code-week-4#1]
1. Mettre à jour le fichier `README.md`
2. Corriger cette typo `default: #00000` au lieu de `DEFAULT`
3. Le dossiers `logo` doit rester dans le dossiers `assets` et non dans le dossiers `images`

j'ai pas grand chose à ajouter. Beau boulot

**Comment by adeys** [comment]
Merci beaucoup à vous.
Je vais les intégrer
